### ISSUE TITLE
Memory Crash due to high values

### ISSUE THREAD

**Issue by DefinetlyNotAI** [leedave/flipper-zero-meal-pager#28]
Setting the Station and Pager values to large values then running them results in memory crashes on the flipper, maybe add warnings?

**Comment by leedave** [comment]
Not sure how far I want to take this. Currently most people who want the app need to learn how to build it, so they should have a little more knowledge than those who just want to fool around with it. But yes, warnings should be enough, if someone crashes the flipper by taking things too far, it's their own fault. 

I'll keep this open as feature request for now.

**Comment by DefinetlyNotAI** [comment]
Ok, I will unsub from this, but not close this, after my O level's I may come back to fork and PR this feature, as a patch, and then i leave the rest to you, great app btw

**Comment by DefinetlyNotAI** [comment]
Alright - I will most likely work on this :)

**Comment by DefinetlyNotAI** [comment]
lol, changed my mind - i dont have enough time to understand the whole code...
Sorry lol
